services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '1.0'      # Limita a 1 CPU
          memory: 512M     # Limita a 512 MB de RAM
        reservations:
          cpus: '0.5'      # Reserva 0.5 CPU
          memory: 256M     # Reserva 256 MB de RAM

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: node src/server.js
    deploy:
      replicas: 3